### PR TITLE
made hashers return only positive values (add Math.abs)

### PR DESCRIPTION
**Pull request by jwijgerd**

### CODE REVIEW

**Comment by andrebrait** [comment]
What's the context here?

**Comment by jwijgerd** [comment]
I see the issue now, you are doing Math.abs in the LocalActorSystemInstance. This was not changed in the kafka module (which I'm dusting off) hence it was failing

**Comment by jwijgerd** [comment]
I will just change it in the kafka module and then we can close this PR

**Comment by jwijgerd** [comment]
closing as invalid

**Pull request closed without merging**
